// <auto-generated />
using System;
using API_ProyectoProg1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_ProyectoProg1.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231205174039_ActualizarCLiente")]
    partial class ActualizarCLiente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_ProyectoProg1.Models.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Cedula = "1234567890",
                            Apellido = "Apellido1",
                            Contrasenia = "contraseña1",
                            Correo = "cliente1@example.com",
                            Direccion = "Dirección1",
                            Nombre = "Nombre1",
                            Telefono = "123-456-7890"
                        },
                        new
                        {
                            Cedula = "0987654321",
                            Apellido = "Apellido2",
                            Contrasenia = "contraseña2",
                            Correo = "cliente2@example.com",
                            Direccion = "Dirección2",
                            Nombre = "Nombre2",
                            Telefono = "987-654-3210"
                        });
                });

            modelBuilder.Entity("API_ProyectoProg1.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<string>("CedulaAutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdComentario");

                    b.ToTable("Comentario");

                    b.HasData(
                        new
                        {
                            IdComentario = 1,
                            CedulaAutor = "1234567890",
                            Fecha = new DateTime(2023, 12, 5, 12, 40, 39, 291, DateTimeKind.Local).AddTicks(5866),
                            Mensaje = "Este es un comentario de ejemplo 1.",
                            NombreAutor = "Nombre del Autor 1"
                        },
                        new
                        {
                            IdComentario = 2,
                            CedulaAutor = "0987654321",
                            Fecha = new DateTime(2023, 12, 5, 11, 40, 39, 291, DateTimeKind.Local).AddTicks(5883),
                            Mensaje = "Este es un comentario de ejemplo 2.",
                            NombreAutor = "Nombre del Autor 2"
                        });
                });

            modelBuilder.Entity("API_ProyectoProg1.Models.Distribuidor", b =>
                {
                    b.Property<int>("IdDistribuidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDistribuidor"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCompra")
                        .HasColumnType("int");

                    b.HasKey("IdDistribuidor");

                    b.ToTable("Distribuidor");

                    b.HasData(
                        new
                        {
                            IdDistribuidor = 1234,
                            Contacto = "0987654321",
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            NumeroCompra = 12
                        },
                        new
                        {
                            IdDistribuidor = 4567,
                            Contacto = "0987654321",
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            NumeroCompra = 12
                        },
                        new
                        {
                            IdDistribuidor = 7890,
                            Contacto = "0987654321",
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            NumeroCompra = 12
                        });
                });

            modelBuilder.Entity("API_ProyectoProg1.Models.Pedido", b =>
                {
                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdDistribuidor")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecioDocena")
                        .HasColumnType("float");

                    b.Property<double>("PrecioVentaUnid")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedido");

                    b.HasData(
                        new
                        {
                            PedidoId = "70",
                            IdDistribuidor = 7890,
                            Marca = "Marca 3",
                            Nombre = "Producto pedido",
                            PrecioDocena = 35.0,
                            PrecioVentaUnid = 5.75,
                            Stock = 1,
                            Tipo = "Ropa Interior"
                        });
                });

            modelBuilder.Entity("API_ProyectoProg1.Models.Ropa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdDistribuidor")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecioDocena")
                        .HasColumnType("float");

                    b.Property<double>("PrecioVentaUnid")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Ropa");

                    b.HasData(
                        new
                        {
                            Codigo = "1234",
                            IdDistribuidor = 1234,
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            PrecioDocena = 78.0,
                            PrecioVentaUnid = 6.5,
                            Stock = 12,
                            Tipo = "Ropa Interior"
                        },
                        new
                        {
                            Codigo = "4567RP",
                            IdDistribuidor = 4567,
                            Marca = "Marca 2",
                            Nombre = "Producto 2",
                            PrecioDocena = 20.539999999999999,
                            PrecioVentaUnid = 2.25,
                            Stock = 4,
                            Tipo = "Medias"
                        },
                        new
                        {
                            Codigo = "7890RP",
                            IdDistribuidor = 7890,
                            Marca = "Marca 3",
                            Nombre = "Producto 3",
                            PrecioDocena = 35.0,
                            PrecioVentaUnid = 5.75,
                            Stock = 10,
                            Tipo = "Ropa Interior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
