// <auto-generated />
using API_ProyectoProg1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_ProyectoProg1.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231031125902_CrearTablaPedido")]
    partial class CrearTablaPedido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_ProyectoProg1.Models.Distribuidor", b =>
                {
                    b.Property<int>("IdDistribuidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDistribuidor"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCompra")
                        .HasColumnType("int");

                    b.HasKey("IdDistribuidor");

                    b.ToTable("Distribuidor");

                    b.HasData(
                        new
                        {
                            IdDistribuidor = 1234,
                            Contacto = "0987654321",
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            NumeroCompra = 12
                        },
                        new
                        {
                            IdDistribuidor = 4567,
                            Contacto = "0987654321",
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            NumeroCompra = 12
                        },
                        new
                        {
                            IdDistribuidor = 7890,
                            Contacto = "0987654321",
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            NumeroCompra = 12
                        });
                });

            modelBuilder.Entity("API_ProyectoProg1.Models.Pedido", b =>
                {
                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdDistribuidor")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecioDocena")
                        .HasColumnType("float");

                    b.Property<double>("PrecioVentaUnid")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedido");

                    b.HasData(
                        new
                        {
                            PedidoId = "70",
                            IdDistribuidor = 7890,
                            Marca = "Marca 3",
                            Nombre = "Producto pedido",
                            PrecioDocena = 35.0,
                            PrecioVentaUnid = 5.75,
                            Stock = 1,
                            Tipo = "Ropa Interior"
                        });
                });

            modelBuilder.Entity("API_ProyectoProg1.Models.Ropa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdDistribuidor")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecioDocena")
                        .HasColumnType("float");

                    b.Property<double>("PrecioVentaUnid")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Ropa");

                    b.HasData(
                        new
                        {
                            Codigo = "1234",
                            IdDistribuidor = 1234,
                            Marca = "Roland",
                            Nombre = "Calzoncillos 1",
                            PrecioDocena = 78.0,
                            PrecioVentaUnid = 6.5,
                            Stock = 12,
                            Tipo = "Ropa Interior"
                        },
                        new
                        {
                            Codigo = "4567RP",
                            IdDistribuidor = 4567,
                            Marca = "Marca 2",
                            Nombre = "Producto 2",
                            PrecioDocena = 20.539999999999999,
                            PrecioVentaUnid = 2.25,
                            Stock = 4,
                            Tipo = "Medias"
                        },
                        new
                        {
                            Codigo = "7890RP",
                            IdDistribuidor = 7890,
                            Marca = "Marca 3",
                            Nombre = "Producto 3",
                            PrecioDocena = 35.0,
                            PrecioVentaUnid = 5.75,
                            Stock = 10,
                            Tipo = "Ropa Interior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
